// Blog posts data that can be shared across components
export const blogPosts = [
  {
    id: 1,
    title: "Empowering Communities Through Digital Literacy",
    excerpt: "How our digital literacy programs are creating new opportunities for underserved communities.",
    date: "March 15, 2023",
    author: "Jane Smith",
    category: "Education",
    image: "/placeholder.svg?height=600&width=800",
    slug: "empowering-communities-digital-literacy",
  },
  {
    id: 2,
    title: "The Impact of Mentorship on Career Development",
    excerpt: "Exploring how mentorship programs can significantly enhance career growth and professional development.",
    date: "February 28, 2023",
    author: "John Doe",
    category: "Career",
    image: "/placeholder.svg?height=600&width=800",
    slug: "impact-mentorship-career-development",
  },
  {
    id: 3,
    title: "Building Sustainable Partnerships for Long-term Success",
    excerpt: "Strategies for creating and maintaining partnerships that drive mutual growth and community impact.",
    date: "January 20, 2023",
    author: "Sarah Johnson",
    category: "Partnerships",
    image: "/placeholder.svg?height=600&width=800",
    slug: "building-sustainable-partnerships",
  },
  {
    id: 4,
    title: "Innovative Approaches to Youth Employment",
    excerpt: "New methods and programs we're implementing to address youth unemployment in urban areas.",
    date: "December 12, 2022",
    author: "Michael Brown",
    category: "Employment",
    image: "/placeholder.svg?height=600&width=800",
    slug: "innovative-approaches-youth-employment",
  },
  {
    id: 5,
    title: "The Role of Technology in Creating Equal Opportunities",
    excerpt: "How technology is being leveraged to level the playing field and create more inclusive opportunities.",
    date: "November 5, 2022",
    author: "Lisa Chen",
    category: "Technology",
    image: "/placeholder.svg?height=600&width=800",
    slug: "role-technology-equal-opportunities",
  },
  {
    id: 6,
    title: "Success Stories: From Training to Employment",
    excerpt: "Real-life success stories of individuals who transformed their careers through our programs.",
    date: "October 18, 2022",
    author: "David Wilson",
    category: "Success Stories",
    image: "/placeholder.svg?height=600&width=800",
    slug: "success-stories-training-employment",
  },
]

// Categories for blog filtering
export const blogCategories = [
  "Education",
  "Career",
  "Partnerships",
  "Employment",
  "Technology",
  "Success Stories",
  "Events",
  "Community",
]
